<a href="https://colab.research.google.com/github/roshan-shaik-ml/Deep-Learning-from-Scratch/blob/main/1.Foundations/Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

### Code Caveat #1. Numpy

In [35]:
print("Python list operations:")
a = [1, 2, 3]
b = [4, 5, 6]
print("a+b:", a+b)

Python list operations:
a+b: [1, 2, 3, 4, 5, 6]


In [36]:
try:
    print(a*b)
except TypeError:
    print("a*b has no meaning for python lists")

a*b has no meaning for python lists


In [37]:
print("numpy array operations:")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a+b:", a+b)
print("a*b:", a*b)

numpy array operations:
a+b: [5 7 9]
a*b: [ 4 10 18]


In [38]:
a = np.array([[1, 2], [3, 4]])
print("a:")
print(a)
print("a.sum(axis=0):", a.sum(axis=0))
print("a.sum(axis=1):", a.sum(axis=1))

a:
[[1 2]
 [3 4]]
a.sum(axis=0): [4 6]
a.sum(axis=1): [3 7]


In [39]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b= np.array([10, 20, 30])

print("a+b:\n", a+b)

a+b:
 [[11 22 33]
 [14 25 36]]


### Code caveat #2. Numpy

In [40]:
from numpy import ndarray

In [41]:
def square(x: ndarray):

    ''' 
    Squares each element in the input array.
    '''
    return np.power(x, 2)

In [42]:
def leaky_relu(x: ndarray):

    ''' 
    Apply "Leaky ReLU function to each element in ndarray.
    '''
    return np.maximum(0.2 * x, x)

In [43]:
square_sample = np.arange(5)
relu_sample = np.random.rand(3, 2)
print("Square:\n", square(square_sample))
print("Leaky ReLU:\n", leaky_relu(relu_sample))

Square:
 [ 0  1  4  9 16]
Leaky ReLU:
 [[0.43659148 0.66408372]
 [0.84239643 0.45792103]
 [0.58696815 0.30490507]]
